const translations = {
  sr: {
    navAbout:'O nama',navServices:'Usluge',navProcess:'Proces',navGallery:'Galerija',navContact:'Kontakt',
    eyebrow:'Profesionalni travnati sportski tereni',heroTitle:'Izgradnja, rekonstrukcija i održavanje sportskih terena',heroText:'SPORT-GRADNJA Pirot je specijalizovana za travnate terene, proizvodnju i postavljanje busena, nivelaciju, zalivanje, sanaciju i redovno održavanje zelenih sportskih površina.',ctaQuote:'Zatraži ponudu',ctaWorks:'Pogledaj radove',statYears:'godina iskustva',statGrass:'prirodna trava',statCare:'briga o terenu',
    aboutKicker:'O kompaniji',aboutTitle:'Specijalisti za sportske i zelene površine',aboutP1:'Bavimo se izgradnjom, rekonstrukcijom, saniranjem i održavanjem sportskih terena i travnatih površina. Fokus je na kvalitetnoj pripremi podloge, pravilnoj ugradnji busena i dugoročnom održavanju terena.',aboutP2:'Naš rad obuhvata fudbalske terene, pomoćne terene, školske i rekreativne površine, kao i sve zelene površine koje zahtevaju preciznost, kvalitetnu drenažu, nivelaciju i negu.',
    servicesKicker:'Šta radimo',servicesTitle:'Kompletna usluga za travnate sportske terene',service1Title:'Izgradnja terena',service1Text:'Priprema podloge, nivelacija, drenaža i kompletno formiranje travnate sportske površine.',service2Title:'Postavljanje busena',service2Text:'Sečenje, rolanje, transport i ugradnja prirodnog travnatog busena.',service3Title:'Rekonstrukcija',service3Text:'Saniranje oštećenih delova terena, popravka neravnina i obnova travnatog pokrivača.',service4Title:'Održavanje',service4Text:'Košenje, zalivanje, aeracija, prihrana i redovna nega terena tokom sezone.',
    processKicker:'Način rada',processTitle:'Od procene terena do spremne travnate površine',processText:'Svaki projekat počinje pregledom lokacije i planiranjem radova. Nakon pripreme podloge, busen se seče, doprema, postavlja i neguje dok teren ne bude spreman za korišćenje.',step1:'Pregled i planiranje radova',step2:'Priprema, nivelacija i drenaža',step3:'Ugradnja busena i završno ravnanje',step4:'Zalivanje, košenje i održavanje',noteTitle:'Prirodna trava',noteText:'Rešenje za profesionalne i rekreativne sportske terene.',
    galleryKicker:'Galerija',galleryTitle:'Radovi, oprema i travnati tereni',gal1:'Mašina za sečenje busena',gal2:'Sečenje i priprema busena',gal3:'Busen pripremljen za utovar',gal4:'Nasečen busen na terenu',gal5:'Rolanje busena',gal6:'Utovar i transport',gal7:'Istovar busena na stadionu',gal8:'Priprema travnate površine',gal9:'Specijalizovana oprema',gal10:'Košenje i održavanje',gal11:'Sanacija oštećenja',gal12:'Zalivanje terena',
    refsKicker:'Reference',refsTitle:'Iskustvo na sportskim terenima',refsText:'Radovi i održavanje travnatih površina za profesionalne i rekreativne sportske objekte.',ref3:'Sportski i rekreativni tereni',contactKicker:'Kontakt',contactTitle:'Planirate izgradnju ili obnovu terena?',contactText:'Pošaljite upit za procenu, rekonstrukciju ili održavanje travnate površine. Tim SPORT-GRADNJA Pirot može da predloži optimalan način rada u skladu sa stanjem terena.',addressLabel:'Adresa:',phoneLabel:'Telefon:',sendMail:'Pošalji email',contactNote:'Telefon možeš promeniti u fajlu index.html kada budeš imao tačan broj.',footerText:'Modernizovana responsive prezentacija.'
  },
  en: {
    navAbout:'About',navServices:'Services',navProcess:'Process',navGallery:'Gallery',navContact:'Contact',
    eyebrow:'Professional natural-grass sports fields',heroTitle:'Construction, reconstruction and maintenance of sports fields',heroText:'SPORT-GRADNJA Pirot specializes in natural-grass fields, turf production and installation, grading, irrigation, repair and regular maintenance of green sports surfaces.',ctaQuote:'Request an offer',ctaWorks:'View works',statYears:'years of experience',statGrass:'natural grass',statCare:'field care',
    aboutKicker:'About the company',aboutTitle:'Specialists for sports and green areas',aboutP1:'We build, reconstruct, repair and maintain sports fields and grass surfaces. Our focus is high-quality ground preparation, proper turf installation and long-term field care.',aboutP2:'Our work covers football fields, training fields, school and recreational areas, as well as all green surfaces that require precision, quality drainage, grading and care.',
    servicesKicker:'What we do',servicesTitle:'Complete service for natural-grass sports fields',service1Title:'Field construction',service1Text:'Ground preparation, grading, drainage and complete formation of the grass sports surface.',service2Title:'Turf installation',service2Text:'Cutting, rolling, transport and installation of natural turf.',service3Title:'Reconstruction',service3Text:'Repair of damaged field areas, correction of uneven surfaces and renewal of grass cover.',service4Title:'Maintenance',service4Text:'Mowing, irrigation, aeration, fertilization and regular seasonal field care.',
    processKicker:'How we work',processTitle:'From field assessment to a ready grass surface',processText:'Every project starts with site inspection and work planning. After the base is prepared, turf is cut, delivered, installed and maintained until the field is ready for use.',step1:'Inspection and work planning',step2:'Preparation, grading and drainage',step3:'Turf installation and final leveling',step4:'Irrigation, mowing and maintenance',noteTitle:'Natural grass',noteText:'A solution for professional and recreational sports fields.',
    galleryKicker:'Gallery',galleryTitle:'Works, equipment and grass fields',gal1:'Turf cutter machine',gal2:'Turf cutting and preparation',gal3:'Turf prepared for loading',gal4:'Cut turf on the field',gal5:'Turf rolling',gal6:'Loading and transport',gal7:'Unloading turf at the stadium',gal8:'Grass surface preparation',gal9:'Specialized equipment',gal10:'Mowing and maintenance',gal11:'Damage repair',gal12:'Field irrigation',
    refsKicker:'References',refsTitle:'Experience on sports fields',refsText:'Works and maintenance of grass surfaces for professional and recreational sports facilities.',ref3:'Sports and recreational fields',contactKicker:'Contact',contactTitle:'Planning to build or renew a field?',contactText:'Send an inquiry for assessment, reconstruction or maintenance of a grass surface. SPORT-GRADNJA Pirot can suggest the optimal method according to the field condition.',addressLabel:'Address:',phoneLabel:'Phone:',sendMail:'Send email',contactNote:'You can change the phone number in index.html when you have the correct one.',footerText:'Modernized responsive presentation.'
  },
  de: {
    navAbout:'Über uns',navServices:'Leistungen',navProcess:'Ablauf',navGallery:'Galerie',navContact:'Kontakt',
    eyebrow:'Professionelle Naturrasen-Sportplätze',heroTitle:'Bau, Rekonstruktion und Pflege von Sportplätzen',heroText:'SPORT-GRADNJA Pirot ist spezialisiert auf Naturrasenplätze, Produktion und Verlegung von Rollrasen, Nivellierung, Bewässerung, Sanierung und regelmäßige Pflege grüner Sportflächen.',ctaQuote:'Angebot anfragen',ctaWorks:'Arbeiten ansehen',statYears:'Jahre Erfahrung',statGrass:'Naturrasen',statCare:'Platzpflege',
    aboutKicker:'Über das Unternehmen',aboutTitle:'Spezialisten für Sport- und Grünflächen',aboutP1:'Wir bauen, rekonstruieren, sanieren und pflegen Sportplätze und Rasenflächen. Im Mittelpunkt stehen hochwertige Untergrundvorbereitung, fachgerechte Rasenverlegung und langfristige Platzpflege.',aboutP2:'Unsere Arbeit umfasst Fußballplätze, Trainingsplätze, Schul- und Freizeitflächen sowie alle Grünflächen, die Präzision, hochwertige Drainage, Nivellierung und Pflege erfordern.',
    servicesKicker:'Was wir tun',servicesTitle:'Kompletter Service für Naturrasen-Sportplätze',service1Title:'Platzbau',service1Text:'Untergrundvorbereitung, Nivellierung, Drainage und vollständige Erstellung der Rasen-Sportfläche.',service2Title:'Rasenverlegung',service2Text:'Schneiden, Rollen, Transport und Verlegung von Naturrasen.',service3Title:'Rekonstruktion',service3Text:'Sanierung beschädigter Platzbereiche, Ausgleich von Unebenheiten und Erneuerung der Rasendecke.',service4Title:'Pflege',service4Text:'Mähen, Bewässerung, Aerifizierung, Düngung und regelmäßige saisonale Pflege.',
    processKicker:'Arbeitsweise',processTitle:'Von der Platzanalyse bis zur fertigen Rasenfläche',processText:'Jedes Projekt beginnt mit einer Besichtigung und Arbeitsplanung. Nach der Vorbereitung des Untergrunds wird der Rasen geschnitten, geliefert, verlegt und gepflegt, bis der Platz nutzbar ist.',step1:'Besichtigung und Planung',step2:'Vorbereitung, Nivellierung und Drainage',step3:'Rasenverlegung und Endnivellierung',step4:'Bewässerung, Mähen und Pflege',noteTitle:'Naturrasen',noteText:'Eine Lösung für professionelle und freizeitliche Sportplätze.',
    galleryKicker:'Galerie',galleryTitle:'Arbeiten, Ausrüstung und Rasenplätze',gal1:'Rasenschneidemaschine',gal2:'Schneiden und Vorbereitung des Rasens',gal3:'Rasen für den Transport vorbereitet',gal4:'Geschnittener Rasen auf dem Feld',gal5:'Rasenrollen',gal6:'Beladung und Transport',gal7:'Entladung des Rasens im Stadion',gal8:'Vorbereitung der Rasenfläche',gal9:'Spezialausrüstung',gal10:'Mähen und Pflege',gal11:'Schadensanierung',gal12:'Bewässerung des Platzes',
    refsKicker:'Referenzen',refsTitle:'Erfahrung auf Sportplätzen',refsText:'Arbeiten und Pflege von Rasenflächen für professionelle und freizeitliche Sportanlagen.',ref3:'Sport- und Freizeitplätze',contactKicker:'Kontakt',contactTitle:'Planen Sie den Bau oder die Erneuerung eines Platzes?',contactText:'Senden Sie eine Anfrage für Bewertung, Rekonstruktion oder Pflege einer Rasenfläche. SPORT-GRADNJA Pirot kann die optimale Arbeitsweise entsprechend dem Zustand des Platzes vorschlagen.',addressLabel:'Adresse:',phoneLabel:'Telefon:',sendMail:'E-Mail senden',contactNote:'Die Telefonnummer kann in index.html geändert werden, sobald die richtige Nummer vorhanden ist.',footerText:'Modernisierte responsive Präsentation.'
  },
  fr: {
    navAbout:'À propos',navServices:'Services',navProcess:'Processus',navGallery:'Galerie',navContact:'Contact',
    eyebrow:'Terrains de sport en gazon naturel',heroTitle:'Construction, rénovation et entretien de terrains de sport',heroText:'SPORT-GRADNJA Pirot est spécialisée dans les terrains en gazon naturel, la production et la pose de gazon en rouleaux, le nivellement, l’arrosage, la réparation et l’entretien régulier des surfaces sportives.',ctaQuote:'Demander une offre',ctaWorks:'Voir les travaux',statYears:'ans d’expérience',statGrass:'gazon naturel',statCare:'entretien du terrain',
    aboutKicker:'À propos de l’entreprise',aboutTitle:'Spécialistes des surfaces sportives et espaces verts',aboutP1:'Nous construisons, rénovons, réparons et entretenons des terrains de sport et des surfaces en gazon. Notre priorité est la bonne préparation du sol, la pose correcte du gazon et l’entretien durable du terrain.',aboutP2:'Notre travail couvre les terrains de football, terrains d’entraînement, espaces scolaires et récréatifs, ainsi que toutes les surfaces vertes nécessitant précision, drainage, nivellement et soin.',
    servicesKicker:'Ce que nous faisons',servicesTitle:'Service complet pour terrains de sport en gazon naturel',service1Title:'Construction de terrains',service1Text:'Préparation du sol, nivellement, drainage et création complète de la surface sportive en gazon.',service2Title:'Pose de gazon',service2Text:'Découpe, roulage, transport et installation de gazon naturel.',service3Title:'Rénovation',service3Text:'Réparation des zones endommagées, correction des irrégularités et renouvellement du couvert végétal.',service4Title:'Entretien',service4Text:'Tonte, arrosage, aération, fertilisation et entretien régulier pendant la saison.',
    processKicker:'Méthode de travail',processTitle:'De l’évaluation du terrain à une surface prête à l’emploi',processText:'Chaque projet commence par une visite du site et une planification. Après la préparation de la base, le gazon est découpé, livré, posé et entretenu jusqu’à ce que le terrain soit prêt.',step1:'Inspection et planification',step2:'Préparation, nivellement et drainage',step3:'Pose du gazon et nivellement final',step4:'Arrosage, tonte et entretien',noteTitle:'Gazon naturel',noteText:'Une solution pour les terrains sportifs professionnels et récréatifs.',
    galleryKicker:'Galerie',galleryTitle:'Travaux, équipement et terrains gazonnés',gal1:'Machine de découpe du gazon',gal2:'Découpe et préparation du gazon',gal3:'Gazon préparé pour le chargement',gal4:'Gazon découpé sur le terrain',gal5:'Roulage du gazon',gal6:'Chargement et transport',gal7:'Déchargement du gazon au stade',gal8:'Préparation de la surface',gal9:'Équipement spécialisé',gal10:'Tonte et entretien',gal11:'Réparation des dommages',gal12:'Arrosage du terrain',
    refsKicker:'Références',refsTitle:'Expérience sur terrains de sport',refsText:'Travaux et entretien de surfaces gazonnées pour installations sportives professionnelles et récréatives.',ref3:'Terrains sportifs et récréatifs',contactKicker:'Contact',contactTitle:'Vous prévoyez de construire ou rénover un terrain ?',contactText:'Envoyez une demande pour l’évaluation, la rénovation ou l’entretien d’une surface gazonnée. SPORT-GRADNJA Pirot peut proposer la meilleure méthode selon l’état du terrain.',addressLabel:'Adresse :',phoneLabel:'Téléphone :',sendMail:'Envoyer un email',contactNote:'Vous pouvez modifier le numéro de téléphone dans index.html lorsque vous avez le bon numéro.',footerText:'Présentation responsive modernisée.'
  },
  bg: {
    navAbout:'За нас',navServices:'Услуги',navProcess:'Процес',navGallery:'Галерия',navContact:'Контакт',
    eyebrow:'Професионални спортни терени с естествена трева',heroTitle:'Изграждане, реконструкция и поддръжка на спортни терени',heroText:'SPORT-GRADNJA Pirot е специализирана в тревни терени, производство и полагане на тревен чим, нивелиране, напояване, ремонт и редовна поддръжка на зелени спортни площи.',ctaQuote:'Поискайте оферта',ctaWorks:'Вижте проектите',statYears:'години опит',statGrass:'естествена трева',statCare:'грижа за терена',
    aboutKicker:'За компанията',aboutTitle:'Специалисти за спортни и зелени площи',aboutP1:'Занимаваме се с изграждане, реконструкция, ремонт и поддръжка на спортни терени и тревни площи. Фокусът ни е върху качествена подготовка на основата, правилно полагане на чима и дългосрочна поддръжка.',aboutP2:'Работим по футболни терени, тренировъчни терени, училищни и рекреационни площи, както и по всички зелени площи, които изискват прецизност, качествен дренаж, нивелиране и грижа.',
    servicesKicker:'Какво правим',servicesTitle:'Пълна услуга за спортни терени с естествена трева',service1Title:'Изграждане на терени',service1Text:'Подготовка на основата, нивелиране, дренаж и цялостно оформяне на тревната спортна площ.',service2Title:'Полагане на чим',service2Text:'Рязане, навиване, транспорт и монтаж на естествен тревен чим.',service3Title:'Реконструкция',service3Text:'Ремонт на повредени части на терена, корекция на неравности и обновяване на тревната покривка.',service4Title:'Поддръжка',service4Text:'Косене, напояване, аерация, подхранване и редовна сезонна поддръжка.',
    processKicker:'Начин на работа',processTitle:'От оглед на терена до готова тревна площ',processText:'Всеки проект започва с оглед на мястото и планиране на работите. След подготовката на основата чимът се реже, доставя, полага и поддържа, докато теренът стане готов за използване.',step1:'Оглед и планиране',step2:'Подготовка, нивелиране и дренаж',step3:'Полагане на чим и финално изравняване',step4:'Напояване, косене и поддръжка',noteTitle:'Естествена трева',noteText:'Решение за професионални и рекреационни спортни терени.',
    galleryKicker:'Галерия',galleryTitle:'Работа, оборудване и тревни терени',gal1:'Машина за рязане на чим',gal2:'Рязане и подготовка на чим',gal3:'Чим, подготвен за товарене',gal4:'Нарязан чим на терена',gal5:'Навиване на чим',gal6:'Товарене и транспорт',gal7:'Разтоварване на чим на стадион',gal8:'Подготовка на тревната площ',gal9:'Специализирано оборудване',gal10:'Косене и поддръжка',gal11:'Ремонт на повреди',gal12:'Напояване на терена',
    refsKicker:'Референции',refsTitle:'Опит със спортни терени',refsText:'Работа и поддръжка на тревни площи за професионални и рекреационни спортни обекти.',ref3:'Спортни и рекреационни терени',contactKicker:'Контакт',contactTitle:'Планирате изграждане или обновяване на терен?',contactText:'Изпратете запитване за оценка, реконструкция или поддръжка на тревна площ. Екипът на SPORT-GRADNJA Pirot може да предложи оптимален подход според състоянието на терена.',addressLabel:'Адрес:',phoneLabel:'Телефон:',sendMail:'Изпрати email',contactNote:'Телефонът може да се промени във файла index.html, когато имате точния номер.',footerText:'Модернизирана responsive презентация.'
  }
};

function setLanguage(lang){
  const dict = translations[lang] || translations.sr;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if(dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll('[data-lang]').forEach(btn => btn.classList.toggle('active', btn.dataset.lang === lang));
  localStorage.setItem('sg-lang', lang);
}

document.querySelectorAll('[data-lang]').forEach(btn => btn.addEventListener('click', () => setLanguage(btn.dataset.lang)));
document.getElementById('year').textContent = new Date().getFullYear();
const toggle = document.querySelector('.nav-toggle');
const nav = document.querySelector('.main-nav');
toggle.addEventListener('click', () => {const open = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded', open ? 'true' : 'false');});
document.querySelectorAll('.main-nav a').forEach(a => a.addEventListener('click', () => nav.classList.remove('open')));
setLanguage(localStorage.getItem('sg-lang') || 'sr');
